# Generated by Django 2.2.7 on 2020-11-02 01:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('rest_address', models.CharField(max_length=100)),
                ('rest_high', models.CharField(max_length=100, null=True)),
                ('rest_highdirect', models.CharField(max_length=100, null=True)),
                ('rest_coordinate', models.CharField(max_length=100)),
                ('rest_fix', models.BooleanField(default=False)),
                ('rest_truck', models.BooleanField(default=False)),
                ('rest_feeding', models.BooleanField(default=False)),
                ('rest_sleep', models.BooleanField(default=False)),
                ('rest_shower', models.BooleanField(default=False)),
                ('rest_drug', models.BooleanField(default=False)),
                ('rest_laundary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('top_shop', models.CharField(max_length=100)),
                ('top_item', models.CharField(max_length=100)),
                ('rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaults.Rest')),
            ],
        ),
        migrations.CreateModel(
            name='RestMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.CharField(max_length=100)),
                ('menu_best', models.CharField(max_length=100)),
                ('rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaults.Rest')),
            ],
        ),
        migrations.CreateModel(
            name='RestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_create', models.DateTimeField(auto_now_add=True)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaults.Rest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_rest', models.CharField(max_length=100)),
                ('ex_name', models.CharField(max_length=100)),
                ('ex_price', models.CharField(max_length=100)),
                ('ex_img', models.CharField(max_length=100)),
                ('ex_info', models.CharField(max_length=100)),
                ('rest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaults.Rest')),
            ],
        ),
        migrations.CreateModel(
            name='BrandShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_opentime', models.CharField(max_length=100)),
                ('rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaults.Rest')),
            ],
        ),
    ]
